# This is a basic workflow to help you get started with Actions
 
name: CI
 
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile:
    name: Compiler
    runs-on: windows-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Setup Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: Compile Project
        run: |
          msbuild COVID-19_Statistics.sln /property:Configuration=Debug /property:Platform=x64  
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: COVID-19_Statistics-x64-debug-${{ github.run_id }}
          path: ./x64/Debug/
